@extends('layout.main')

@section('content')

<div class="container">
    <h1>Home</h1>
    <p>Fumetti disponibili: <span class="text-danger">{{ $num_comics }}</span> ;</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum ut quas esse repellat id voluptatibus laboriosam nihil nobis ducimus, saepe odit quae culpa quibusdam. Minima adipisci magnam nostrum ullam ex inventore et aliquam voluptas voluptates cumque assumenda ad atque quam quaerat accusamus corrupti fugiat, doloribus laboriosam accusantium a quae quod ipsa velit? Officiis sit minus, labore quia natus odio saepe cupiditate aperiam vero nemo magnam reprehenderit molestias quibusdam perferendis! Nulla a delectus vitae neque nihil blanditiis numquam officiis quae voluptas at corporis suscipit porro inventore expedita amet, rem sit aut. Laboriosam fuga porro sequi aperiam quo dolorum tempore a? Facere cupiditate dignissimos quibusdam vitae placeat excepturi adipisci recusandae distinctio quos repudiandae laboriosam fugiat voluptatibus numquam, harum officia corporis nobis libero, amet fugit rerum ullam architecto labore! Iure fugiat alias ut illo perspiciatis velit suscipit laudantium nostrum at, repellat molestias odit neque rerum totam quas voluptatem itaque et! Recusandae natus sequi velit obcaecati molestiae laudantium minus, id fugit tenetur facilis. Praesentium aspernatur illum illo et! Enim est illum laborum molestias mollitia iste ipsa eius non. Aliquid et quia ullam quam exercitationem saepe amet voluptate beatae debitis suscipit distinctio perferendis minus velit, veritatis rerum dolore laudantium voluptates repudiandae. Harum architecto cupiditate iusto? Voluptatum impedit commodi illo distinctio. Voluptates quae reiciendis nisi unde dolorum quasi sunt, esse, odio voluptate harum rem quisquam provident eius veniam magnam repellendus, voluptatibus ea saepe molestias earum. Fugiat saepe rem, ut commodi ipsum perspiciatis assumenda nostrum magni quia neque, minima vero sequi corrupti inventore soluta, expedita modi deserunt at totam. Alias unde obcaecati mollitia consequatur. Fuga voluptas, aut deleniti totam itaque tempora dolor perferendis distinctio alias laborum eveniet. Adipisci suscipit ullam, voluptas aspernatur vero animi dolor iste placeat aperiam ipsum commodi odio inventore modi fugit accusamus dicta. Maiores eius molestias ullam ut aliquam possimus rerum id hic ducimus?</p>
</div>

@endsection
